### ISSUE TITLE
Questions about the relations.

### ISSUE THREAD

**Issue by LemonQC** [JerryLingjieMei/FALCON-Release#10]
Why the relations between objects are also derived from the concept embeddings?
In abstract_program.py:  new_arg = box_registry(torch.tensor(arg).to(box_registry.device)). In GQA, even the relations are set to 2 ( **hypernym**), such relation is represented as second concept blue.
Am I right? Maybe there exists some misunderstanding.

**Comment by JerryLingjieMei** [comment]
hypernym, samekind and other relations between concepts are not passed via box registry, as in Line 24 of composite.py. They are in the end used as integer indexing, as in Line 29 of gnn.py.

**Comment by LemonQC** [comment]
OK, Thanks for your help. I got it.
