### ISSUE TITLE
Mask file for CLEVR dataset missing

### ISSUE THREAD

**Issue by weiweigu1998** [JerryLingjieMei/FALCON-Release#11]
Hello,

Sorry for bothering again but the mask file mentioned in [this line](https://github.com/JerryLingjieMei/FALCON-Release/blob/master/dataset/clevr/clevr_dataset.py#L16) in the CLEVR dataset reader is missing. I could not find the file either from Jerry's personal website or from the original CLEVR dataset. Can you please help me to get access to this file?
Your help will be appreciated.

**Comment by JerryLingjieMei** [comment]
I have just added it to the assets/ folder.

**Comment by weiweigu1998** [comment]
Thank you for the reply!
