### ISSUE TITLE
The meaning of Visual Representation?

### ISSUE THREAD

**Issue by ghost** [JerryLingjieMei/FALCON-Release#12]
Dear Lingjie,

This work is really fantastic. And I am curious about the visual representation part. Concretely, I want to ask why you give the box (from MaskRCNN) and the whole image into Resnet-34 to get the visual representation for this box.

![Screenshot 2023-02-24 at 9 38 16 AM](https://user-images.githubusercontent.com/17596799/221221361-37aaf3d9-21b6-4284-ae68-a4bedb557cf7.png)

I hope you can clarify this.

Best regards,
Tin

**Comment by JerryLingjieMei** [comment]
This is for extracting visual representation for an object in the image determined by the mask - you can do it in other ways you like, but the method we are using is simple enough.
