### ISSUE TITLE
Some File missing.

### ISSUE THREAD

**Issue by LemonQC** [JerryLingjieMei/FALCON-Release#2]
![image](https://user-images.githubusercontent.com/30914380/200773838-cd209f2c-14a6-4c8d-9aa8-7a0417e31167.png)
FileNotFoundError: [Errno 2] No such file or directory: '/FALCON-Release-master/download_data/CUB-200-2011/classes.txt'

**Comment by JerryLingjieMei** [comment]
When you download the CUB dataset, there is a class.txt file that is in the same directory as README and images/. Please make sure the directories are correctly placed.

**Comment by LemonQC** [comment]
> When you download the CUB dataset, there is a class.txt file that is in the same directory as README and images/. Please make sure the directories are correctly placed.


Thanks for your reply. I have fixed this issue.
