### ISSUE TITLE
Question about dataset.

### ISSUE THREAD

**Issue by LemonQC** [JerryLingjieMei/FALCON-Release#3]
![image](https://user-images.githubusercontent.com/30914380/200972481-f23f6028-e247-472c-8a0a-258c22604afe.png)

When I run the following script.
`export NAME=cub/cub_support_box; python tools/train_net.py --config-file experiments/${NAME}.yaml`, I face the above problem, while the other scripts are all normal.

When I remove cub_concept_support, I found **augmented/CUB-200-2011/0/cub_concept_support/questions should already exist.**

**Comment by chen0918** [comment]
I also face the same promblem

**Comment by JerryLingjieMei** [comment]
Let me dive into it post cvpr

**Comment by LemonQC** [comment]
> Let me dive into it post cvpr

Good luck and looking forward to your reply.

**Comment by vacuum-cup** [comment]
> Let me dive into it post cvpr
Hello，I aslo face the same problem，Could you provide help for us？

**Comment by LemonQC** [comment]
augmented/CUB-200-2011/0/cub_concept_support/questions should already exist.

> Let me dive into it post cvpr

**Comment by JerryLingjieMei** [comment]
The file is now downloadable from https://people.csail.mit.edu/jerrymei/projects/falcon/assets/ as cub_concept_support.json

**Comment by LemonQC** [comment]
> The file is now downloadable from https://people.csail.mit.edu/jerrymei/projects/falcon/assets/ as cub_concept_support.json

CLEVER_concept_support.json is missing.

**Comment by JerryLingjieMei** [comment]
The file for the split seed zero is now downloadable.
