### ISSUE TITLE
Missing Files or Preprocessing Steps for GQA dataset

### ISSUE THREAD

**Issue by weiweigu1998** [JerryLingjieMei/FALCON-Release#4]
Hello,

I am a graduate student from ASU, and I am trying to use FALCON as our baseline model on my research project. I have been trying to evaluate FALCON on the GQA dataset, but I found that some files listed in the dataset reader for GQA is missing(pretrain_questions.json, sceneGraphs.pkl, refexps.json, fewshot_questions.json, objects/gqa_objects_info.json) as I downloaded the original GQA dataset and ran your download_gqa_data.sh script. Can you please release those files or elaborate on what I need to do to obtain those files? 

Thank you very much!

**Comment by LemonQC** [comment]
> Hello,
> 
> I am a graduate student from ASU, and I am trying to use FALCON as our baseline model on my research project. I have been trying to evaluate FALCON on the GQA dataset, but I found that some files listed in the dataset reader for GQA is missing(pretrain_questions.json, sceneGraphs.pkl, refexps.json, fewshot_questions.json, objects/gqa_objects_info.json) as I downloaded the original GQA dataset and ran your download_gqa_data.sh script. Can you please release those files or elaborate on what I need to do to obtain those files?
> 
> Thank you very much!

I also face the same problem.

**Comment by JerryLingjieMei** [comment]
pretrain_questions.json, refexps.json and fewshot.json are only used for CLEVR dataset for intermediate stages of pertaining question and fewshot question generation, and they are not used in GQA dataset. In GQA data the input to the model are in gqa_concept_support.json and gqa_fewshot.json in https://people.csail.mit.edu/jerrymei/projects/falcon/assets/

sceneGraphs.pkl is also downloadable from the other website now.

gqa_objects_info.json and associated .h5 file are downloadable from https://cs.stanford.edu/people/dorarad/gqa/download.html in Images.zip section.

**Comment by weiweigu1998** [comment]
Thank you for the reply!
