### ISSUE TITLE
The results are lower than the reported performance.

### ISSUE THREAD

**Issue by LemonQC** [JerryLingjieMei/FALCON-Release#5]
We run the following code:
export NAME=cub/cub_fewshot_graphical_box; python tools/test_net.py --config-file experiments/${NAME}.yaml

In  cub_fewshot_graphical_box.yaml, we set
![image](https://user-images.githubusercontent.com/30914380/205312858-380a6834-e8fb-42d5-839a-17a142e9e263.png)

However, we can not obtain the promising results.
![image](https://user-images.githubusercontent.com/30914380/205313057-d4177df6-5c37-4bd8-9929-c3f1d7cfeddc.png)

The other pretrained model obtains 50% accuracy

**Comment by JerryLingjieMei** [comment]
We must remind you that cub_support_box is the pretraining weights for training concepts - You have not trained the fewshot part yet.
