### ISSUE TITLE
The testing process

### ISSUE THREAD

**Issue by LemonQC** [JerryLingjieMei/FALCON-Release#6]
Can the testing process provided in readme reproduce the results? I utilize the code and cannot obtain the performance. 

![image](https://user-images.githubusercontent.com/30914380/205414444-58421100-52e1-46b5-9ab2-862b6b18f289.png)

I  found you provide the last checkpoint (model_0010000.pth), I still obtains inferior performance.

**Comment by JerryLingjieMei** [comment]
Can you elaborate on the specific dataset / config file you are running on?

**Comment by LemonQC** [comment]
> Can you elaborate on the specific dataset / config file you are running on?

export NAME=cub/cub_fewshot_graphical_box; python tools/test_net.py --config-file experiments/${NAME}.yaml

**Comment by cherkkecho** [comment]
Hello, may I ask how you download the dataset, I according to the author of the three commands to download down only "question.json" file, and not the other json data files needed in the programme

**Comment by JerryLingjieMei** [comment]
You can find it in https://people.csail.mit.edu/jerrymei/projects/falcon/assets/
