### ISSUE TITLE
wrong code.

### ISSUE THREAD

**Issue by LemonQC** [JerryLingjieMei/FALCON-Release#8]
No FALCON-R
![image](https://user-images.githubusercontent.com/30914380/206386771-4ec4e4a8-4ab1-4b92-8c8c-708be8b2e4d5.png)
![image](https://user-images.githubusercontent.com/30914380/206386840-5ce7b90a-55a1-4bd1-92b7-b1de862dbe6f.png)

**Comment by vacancy** [comment]
If you look at the forward function, they will be applied in different ways (recurrent vs. a single forward step).

**Comment by LemonQC** [comment]
> If you look at the forward function, they will be applied in different ways (recurrent vs. a single forward step).

Ok, I also found. I think you just utilize the recurrent approach rather that RNN?

**Comment by vacancy** [comment]
RNN basically stands for applying the same neural module (typically named RNNCell in PyTorch) recurrently. So calling it RNN is fine. And at the end this is just a naming for a variable…
