### ISSUE TITLE
Some CLEVR dataset details are missing.

### ISSUE THREAD

**Issue by LemonQC** [JerryLingjieMei/FALCON-Release#9]
I have been trying to evaluate FALCON on the CLEVRdataset, but I found that some files listed in the dataset reader for CLEVR is missing(pretrain_questions.json, refexps.json, fewshot_questions.json,  detectron/CLEVR_train_detect_objs.json) as I downloaded the original CLEVRdataset and ran your download_clevr_data.sh script. Could you offer the download link for clevr that you used and the missing data.
![image](https://user-images.githubusercontent.com/30914380/206396504-1daec9e2-6624-4b3f-9a80-0f3c3f0c517c.png)

![image](https://user-images.githubusercontent.com/30914380/206390306-07ef6a4d-ee1d-4d4b-b800-a5c72dbeb0e7.png)

![image](https://user-images.githubusercontent.com/30914380/206598780-0d6f9c91-f0d7-499b-afab-9a83ae252063.png)

**Comment by LemonQC** [comment]
Does there any responses?

**Comment by JerryLingjieMei** [comment]
Those files can be found at https://people.csail.mit.edu/jerrymei/projects/falcon/assets/0/ 
If you need data for the other three splits, please let me know.
